#!/usr/bin/env bash

mkdir -p $HOME/.composer

TTY_ARGS=()
if [ -t 0 ]; then
  TTY_ARGS=(--interactive --tty)
fi

# @see https://hub.docker.com/_/composer
docker run --rm "${TTY_ARGS[@]}" \
  --volume "$PWD":/app \
  --volume ${COMPOSER_HOME:-$HOME/.composer}:/tmp \
  --user $(id -u):$(id -g) \
  composer:2.7.7 "$@"
